import Link from "next/link";
import { ArrowLeft, BookOpen, Search, Sparkles } from "lucide-react";
import { articles as fallbackArticles, categories as fallbackCategories, brand } from "../lib/content";
import { databaseConfigured, getCategories, getPublishedArticles } from "../lib/content-server";
import { ArticleCard } from "../components/ArticleCard";

export const revalidate = 300;
export default async function Home() { const [dbArticles, dbCategories] = await Promise.all([getPublishedArticles(), getCategories()]); const articles = dbArticles.length || databaseConfigured ? dbArticles : fallbackArticles; const categories = dbCategories.length || databaseConfigured ? dbCategories : fallbackCategories; return <main>
  <section className="hero"><div className="container hero-grid"><div><div className="kicker">Arevan · دانش تخصصی برای تصمیم‌های دقیق‌تر</div><h1><span>آروان</span><br/>دانش تخصصی برای مسائل مالیاتی و مالی</h1><p>آروان، یک مرجع مستقل فارسی برای مطالعه مطالب کاربردی درباره مالیات، دادرسی مالیاتی، حسابداری و حسابرسی است؛ با تمرکز بر توضیح روشن موضوعات حرفه‌ای.</p><div className="actions"><Link className="button button-primary" href="/articles">مطالعه مقالات <ArrowLeft size={17}/></Link><Link className="button button-secondary" href="/search">جستجو در آروان</Link></div><form action="/search" className="search-form hero-search"><input className="input" name="q" placeholder="موضوع مورد نظرتان را جستجو کنید…" aria-label="جستجو در مقالات آروان"/><button className="button button-primary" aria-label="جستجو"><Search size={18}/></button></form></div><div className="hero-note"><img className="note-mark" src="/arevan-logo.svg" alt="آروان" width="78" height="78"/><span>AREVAN KNOWLEDGE</span><p>{brand.tagline}</p><div className="note-rule"/><small>مالیات · حسابداری · حسابرسی</small></div></div></section>
  <section className="section"><div className="container"><div className="section-head"><div><div className="kicker">حوزه‌های دانشی</div><h2>موضوعات را دنبال کنید</h2></div><p className="section-lead">از یک پرسش مشخص شروع کنید و در میان موضوعات مرتبط، پاسخ‌ها و توضیح‌های کاربردی را بیابید.</p></div><div className="grid-3">{categories.slice(0,6).map((category,i)=><Link className="category-card topic-card" href={`/category/${category.slug}`} key={category.slug}><span className="topic-index">۰{i+1}</span><BookOpen size={19}/><h3>{category.name}</h3><p>{category.description}</p><span className="topic-link">مشاهده مطالب ←</span></Link>)}</div></div></section>
  <section className="section" style={{background:"var(--cream)"}}><div className="container"><div className="section-head"><div><div className="kicker">برای شروع مطالعه</div><h2>مقالات منتخب</h2></div><Link className="text-link" href="/articles">کتابخانه مقالات <ArrowLeft size={16}/></Link></div><div className="article-grid">{articles.filter(a=>a.featured).map(a=><ArticleCard key={a.slug} article={a}/>)}</div></div></section>
  <section className="section"><div className="container editorial"><div><div className="kicker">رویکرد آروان</div><h2>محتوای دقیق، روشن و کاربردی</h2><p>آروان موضوعات تخصصی را با ساختاری قابل فهم ارائه می‌کند. هر مطلب باید به پرسش مشخصی پاسخ دهد، میان اطلاعات و برداشت‌ها تفاوت بگذارد و تا جای ممکن به منابع قابل پیگیری توجه کند.</p><Link className="text-link" href="/about">درباره آروان <ArrowLeft size={16}/></Link></div><div className="editorial-points"><div><Sparkles size={18}/><span><b>کاربردی</b><small>تمرکز بر پرسش‌ها و نیازهای واقعی خوانندگان</small></span></div><div><BookOpen size={18}/><span><b>روشن</b><small>توضیح مرحله‌به‌مرحله مفاهیم پیچیده</small></span></div><div><Search size={18}/><span><b>قابل پیگیری</b><small>توجه به منابع و بازبینی محتوای تخصصی</small></span></div></div></div></section>
  <section className="section latest-band"><div className="container"><div className="section-head"><div><div className="kicker">دانش‌نامه آروان</div><h2>تازه‌ترین مقالات</h2></div><Link className="text-link" href="/articles">همه مقالات <ArrowLeft size={16}/></Link></div><div className="article-grid">{articles.slice(0,4).map(a=><ArticleCard key={a.slug} article={a}/>)}</div></div></section>
  <section className="section explore"><div className="container"><div><div className="kicker">موضوعی را دنبال می‌کنید؟</div><h2>جستجو و کاوش در آروان</h2><p>عنوان مقاله، مفهوم یا دسته‌بندی مورد نظرتان را پیدا کنید.</p></div><Link className="button button-primary" href="/search">جستجو در مطالب <Search size={17}/></Link></div></section>
</main>; }
