export type Category = { name: string; slug: string; description: string };
export type Article = { title: string; slug: string; excerpt: string; category: Category; publishedAt: string; updatedAt: string; readingTime: number; visits: number; ratingTotal: number; ratingCount: number; featured?: boolean; content: string; shortAnswer: string };
export const brand = { name: "Arevan", persianName: "آروان", tagline: "دانش تخصصی برای تصمیم‌های دقیق‌تر", author: "تحریریه آروان", authorSlug: "arevan-editorial", authorBio: "هویت انتشاراتی آروان برای تهیه و تدوین محتوای تخصصی و آموزشی." };
export const categories: Category[] = [
  { name: "مالیات", slug: "maliat", description: "مفاهیم و نکات کاربردی مالیاتی" },
  { name: "دادرسی مالیاتی", slug: "daderesi-maliati", description: "شناخت مسیرهای رسیدگی به مسائل و اختلافات مالیاتی" },
  { name: "قوانین و مقررات مالیاتی", slug: "ghavanin", description: "مطالب آموزشی درباره چارچوب‌ها و منابع مالیاتی" },
  { name: "سامانه مودیان", slug: "samane-moadian", description: "آشنایی با مفاهیم و فرایندهای سامانه مودیان" },
  { name: "حسابداری", slug: "hesabdari", description: "مفاهیم و کاربردهای حسابداری" },
  { name: "حسابرسی", slug: "hesabrasi", description: "آموزش و تحلیل مفاهیم حسابرسی" },
  { name: "آموزش و تحلیل", slug: "amoozesh", description: "یادداشت‌های کاربردی برای یادگیری و تحلیل" }
];
export const articles: Article[] = [
  { title: "اعتراض به برگ تشخیص مالیات چگونه انجام می‌شود؟", slug: "e-eteraz-be-barg-tashkhis", excerpt: "راهنمایی مقدماتی برای شناخت مسیر بررسی اعتراض و آماده‌سازی اسناد مرتبط.", category: categories[1], publishedAt: "۱۴۰۳/۰۹/۱۲", updatedAt: "۱۴۰۳/۰۹/۱۵", readingTime: 6, visits: 0, ratingTotal: 0, ratingCount: 0, featured: true, shortAnswer: "اعتراض موثر با شناخت دقیق موضوع، گردآوری مستندات و استفاده از مسیرهای مرتبط آغاز می‌شود.", content: "## پیش از هر اقدام\n\nاین مقاله نمونه‌ای آموزشی است و باید پیش از انتشار با منابع معتبر و بررسی تخصصی تکمیل شود.\n\n### اسناد را منظم کنید\n\nموضوع اعتراض، اسناد حسابداری و مکاتبات مرتبط را در یک پرونده منظم قرار دهید.\n\n> هر تصمیم مالیاتی باید بر پایه اطلاعات دقیق و قابل بررسی گرفته شود.\n\n### جمع‌بندی\n\nپس از روشن شدن موضوع، مسیر مناسب را از منابع رسمی بررسی کنید." },
  { title: "سامانه مودیان چیست؟", slug: "samane-moadian", excerpt: "نگاهی ساده به مفهوم سامانه مودیان و پرسش‌هایی که پیش از شروع باید پاسخ دهید.", category: categories[3], publishedAt: "۱۴۰۳/۰۸/۲۸", updatedAt: "۱۴۰۳/۰۹/۰۳", readingTime: 5, visits: 0, ratingTotal: 0, ratingCount: 0, featured: true, shortAnswer: "سامانه مودیان بخشی از فرایند دیجیتال ثبت و تبادل اطلاعات مالیاتی است؛ جزئیات آن را از مراجع رسمی بررسی کنید.", content: "## یک تعریف ساده\n\nاین مطلب نمونه است و برای آموزش عمومی نوشته شده است. اطلاعات اجرایی و الزامات جاری باید پیش از انتشار از منبع رسمی بازبینی شوند.\n\n### سوال‌های کلیدی\n\nابتدا مشخص کنید کسب‌وکار شما چه نوع اطلاعاتی تولید می‌کند و کدام فرایندها باید مستندسازی شوند." },
  { title: "حسابرسی مالیاتی چیست؟", slug: "hesabrasi-maliati", excerpt: "تفاوت نگاه حسابرسی با رسیدگی مالیاتی و نقش مستندات در تحلیل حرفه‌ای.", category: categories[5], publishedAt: "۱۴۰۳/۰۸/۱۰", updatedAt: "۱۴۰۳/۰۸/۱۸", readingTime: 7, visits: 0, ratingTotal: 0, ratingCount: 0, shortAnswer: "حسابرسی مالیاتی به بررسی منظم اطلاعات و مستندات مالی از منظر موضوعات مالیاتی می‌پردازد.", content: "## نگاه تحلیلی به حسابرسی\n\nاین متن نمونه است و پیش از انتشار باید با منابع معتبر تکمیل شود.\n\n### مستندات قابل اتکا\n\nشفافیت در ثبت رویدادها، دسترسی به اسناد و توضیح روشن فرض‌ها، پایه یک بررسی حرفه‌ای است." },
  { title: "تفاوت حسابرسی و رسیدگی مالیاتی چیست؟", slug: "tafavot-hesabrasi-residgi", excerpt: "مقایسه‌ای مقدماتی برای مدیران و حسابداران که می‌خواهند مفاهیم را دقیق‌تر بشناسند.", category: categories[5], publishedAt: "۱۴۰۳/۰۷/۲۴", updatedAt: "۱۴۰۳/۰۸/۰۱", readingTime: 5, visits: 0, ratingTotal: 0, ratingCount: 0, shortAnswer: "این دو فرایند هدف و چارچوب متفاوتی دارند، هرچند هر دو به داده‌ها و اسناد مالی تکیه می‌کنند.", content: "## چرا این تفاوت مهم است؟\n\nشناخت تفاوت مفاهیم به انتخاب مسیر درست برای پاسخ‌گویی و آماده‌سازی اطلاعات کمک می‌کند. این محتوای نمونه باید با منابع معتبر تکمیل شود." }
];
export function getArticle(slug: string) { return articles.find((article) => article.slug === slug); }
